# Generated by Django 4.2.2 on 2023-06-20 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RoomModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=25)),
                ('type', models.CharField(choices=[('team', 'Team'), ('focus', 'Focus'), ('conference', 'Conference')], default='', max_length=10)),
                ('capacity', models.PositiveSmallIntegerField(default=1)),
            ],
            options={
                'db_table': 'room',
            },
        ),
    ]
