# Generated by Django 4.2.2 on 2023-06-20 08:31

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('begin_time', models.DateTimeField(default=datetime.datetime.now)),
                ('order_time', models.DateTimeField(default=datetime.datetime.now)),
                ('room', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='book.roommodel')),
            ],
            options={
                'db_table': 'order',
            },
        ),
    ]
